site_name: StoreFront SDK 文档
site_description: StoreFront SDK 参考
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: true
pages:
  - StoreFront SDK: index.md
  - 概述: overview.md
  - API 的工作原理: how-the-api-works.md
  - 请求: requests.md
  - 使用配置元素: using-configuration-elements.md
  - StoreFront Customization SDK: customization-sdk.md
  - SDK 入门: getting-started-with-the-sdk.md
  - 自定义接口: customization-interfaces.md
  - 已知问题: known-issues.md
  - 示例: samples.md
